export const ErrorCode = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  NOVEL_NOT_FOUND: 'NOVEL_NOT_FOUND',
  CHAPTER_NOT_FOUND: 'CHAPTER_NOT_FOUND',
  VOLUME_NOT_FOUND: 'VOLUME_NOT_FOUND',
  CANNOT_PUBLISH: 'CANNOT_PUBLISH',
  RELATION_EXISTS: 'RELATION_EXISTS',
  PROTECTED_ADMIN: 'PROTECTED_ADMIN',
  PATH_EXISTS: 'PATH_EXISTS',
  INVALID_PARENT: 'INVALID_PARENT',
  CHARACTER_NOT_FOUND: 'CHARACTER_NOT_FOUND',
} as const

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode]
