import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { BUILTIN_SKILL_IDS, getSkillCategory, getSkillsCatalogDir } from '@narraverse/skills'
import { parseSkillFileFromDisk } from '@narraverse/skills'

function sqlLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

const catalogDir = getSkillsCatalogDir()
const values: string[] = []

for (const id of BUILTIN_SKILL_IDS) {
  const skillDir = join(catalogDir, id)
  const parsed = parseSkillFileFromDisk(skillDir)
  const nv = parsed.frontmatter.metadata?.narraverse
  const displayName = typeof nv?.displayName === 'string' ? nv.displayName : parsed.frontmatter.name
  const skillMd = readFileSync(join(skillDir, 'SKILL.md'), 'utf8')
  const category = getSkillCategory(id)

  values.push(`(
    ${sqlLiteral(id)},
    ${sqlLiteral(displayName)},
    ${sqlLiteral(String(parsed.frontmatter.description).trim())},
    ${sqlLiteral(category)},
    'official',
    ${sqlLiteral(skillMd)},
    '1.0.0',
    true
  )`)
}

const sql = `-- Seed official builtin skills into skill_catalog (idempotent)
-- Generated by: pnpm exec tsx scripts/generate-skill-catalog-seed.ts

CREATE OR REPLACE FUNCTION public.seed_builtin_skill_catalog()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.skill_catalog LIMIT 1) THEN
    RETURN;
  END IF;

  INSERT INTO public.skill_catalog (
    id, display_name, description, category, license_type, skill_md, version, is_builtin
  ) VALUES
${values.join(',\n')};
END;
$$;

REVOKE ALL ON FUNCTION public.seed_builtin_skill_catalog() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.seed_builtin_skill_catalog() TO authenticated;
GRANT EXECUTE ON FUNCTION public.seed_builtin_skill_catalog() TO service_role;

SELECT public.seed_builtin_skill_catalog();
`

const outPath = join(process.cwd(), 'supabase/migrations/20260614000002_seed_skill_catalog.sql')
writeFileSync(outPath, sql, 'utf8')
console.log(`Wrote ${outPath} (${values.length} skills)`)
