-- Seed official builtin skills into skill_catalog (idempotent)
-- Generated by: pnpm exec tsx scripts/generate-skill-catalog-seed.ts

CREATE OR REPLACE FUNCTION public.seed_builtin_skill_catalog()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.skill_catalog LIMIT 1) THEN
    RETURN;
  END IF;

  INSERT INTO public.skill_catalog (
    id, display_name, description, category, license_type, skill_md, version, is_builtin
  ) VALUES
(
    'chinese-novel-style',
    '中文小说风格',
    '中文长篇小说的基础文笔与节奏要求。用户续写、润色、扩写网文，或在 Ask/Plan/Outline/Worldbook/Agent 模式写作时使用。',
    'writing-style',
    'official',
    '---
name: chinese-novel-style
description: 中文长篇小说的基础文笔与节奏要求。用户续写、润色、扩写网文，或在 Ask/Plan/Outline/Worldbook/Agent 模式写作时使用。
metadata:
  author: narraverse
  version: "1.0.0"
  narraverse:
    displayName: 中文小说风格
    scope: runtime
    license: official
    trigger:
      type: always
---

## 风格要求

- 使用流畅的中文长篇小说叙述节奏，避免翻译腔与口水话
- 多用具象细节（动作、五感、环境），少用抽象形容词堆叠
- 单段不要超过 4-5 行，对话与叙述穿插推进
- 不要复述用户已经写过的剧情，只续写或润色用户指定的部分
- 保持人称、时态与原文一致
',
    '1.0.0',
    true
  ),
(
    'brainstorm-facilitation',
    '脑暴引导',
    '脑暴引导：先铺开再收口，批量抛点子。用户构思、找灵感、开脑洞，或处于 Brainstorm 模式时使用。',
    'brainstorm',
    'official',
    '---
name: brainstorm-facilitation
description: 脑暴引导：先铺开再收口，批量抛点子。用户构思、找灵感、开脑洞，或处于 Brainstorm 模式时使用。
metadata:
  author: narraverse
  version: "1.0.0"
  narraverse:
    displayName: 脑暴引导
    scope: runtime
    license: official
    trigger:
      type: mode-or-text
      modes:
        - brainstorm
      textPattern: 脑暴|头脑风暴|点子|灵感|构思|创意|开脑洞|想一个|想几个
      textFlags: i
---

## 脑暴引导规则

- **铺开优先**：一次给 3-5 个不同方向/角度的方案，不要急着收敛到"最佳答案"
- 每条点子配 1-2 句"为什么有意思"或"反差点在哪"
- 避免泛泛标签（"悬疑""爱情"）——要写到具体场景/冲突/钩子层面
- 在用户挑出方向后**才**深挖细节；没挑之前不要替用户做选择
- 用 ask_user 给出 2-4 个互斥方向让用户挑，比让用户自己描述更高效
',
    '1.0.0',
    true
  ),
(
    'craft-discussion',
    '写作技法讨论',
    '写作技法讨论：把 POV、节奏、对话、弧光等拆成可执行建议。用户问技法，或处于 Craft 模式时使用。',
    'craft',
    'official',
    '---
name: craft-discussion
description: 写作技法讨论：把 POV、节奏、对话、弧光等拆成可执行建议。用户问技法，或处于 Craft 模式时使用。
metadata:
  author: narraverse
  version: "1.0.0"
  narraverse:
    displayName: 写作技法讨论
    scope: runtime
    license: official
    trigger:
      type: mode-or-text
      modes:
        - craft
      textPattern: POV|视角|节奏|对话|弧光|伏笔|冲突|主题|文笔|技法|第一人称|第三人称
      textFlags: i
---

## 写作技法讨论规则

- 回答时区分「原理」和「操作步骤」——读者要的是"明天能怎么改"
- 引用知名作品只用做例证，**不剧透**
- 多用对比（第一人称 vs 第三人称紧贴 / 顺叙 vs 倒叙）让用户感知差异
- 给具体句子级别示范（不要只讲"加强对话"，要给改写前后对比）
- 涉及"什么算好"时承认流派差异，避免单一标准的训诫口吻
',
    '1.0.0',
    true
  ),
(
    'editor-surgical',
    '编辑器手术刀',
    '编辑器手术刀：用 propose_edit 在编辑器提交 diff。用户要求改、润色、优化、重写已有章节，且处于 Agent 模式时使用。',
    'editing',
    'official',
    '---
name: editor-surgical
description: 编辑器手术刀：用 propose_edit 在编辑器提交 diff。用户要求改、润色、优化、重写已有章节，且处于 Agent 模式时使用。
metadata:
  author: narraverse
  version: "1.0.0"
  narraverse:
    displayName: 编辑器手术刀
    scope: runtime
    license: official
    tools:
      - read_chapter
      - propose_edit
    trigger:
      type: mode-and-text
      modes:
        - agent
      textPattern: 改|润色|修|优化|重写|调整|改写|polish|rewrite
      textFlags: i
---

## 编辑器联动规则

- 当用户要求修改、润色、优化、重写**已存在的章节内容**时，必须调用 `propose_edit` 工具
- 不要在对话气泡中输出修改后的全文——通过 `propose_edit` 直接把改动作为 diff 提交到编辑器
- 调用 `propose_edit` 前，先用 `read_chapter` 拿到原文
- 一次只改一处，改动尽量小（"最小改动原则"）
- 给出的 `reasoning` 字段要简短说明为什么这样改（一句话）
',
    '1.0.0',
    true
  ),
(
    'outline-editing',
    '大纲编辑',
    '大纲编辑：读写大纲树节点（卷/章/场景）。用户处于 Outline 大纲模式时使用。',
    'planning',
    'official',
    '---
name: outline-editing
description: 大纲编辑：读写大纲树节点（卷/章/场景）。用户处于 Outline 大纲模式时使用。
metadata:
  author: narraverse
  version: "1.0.0"
  narraverse:
    displayName: 大纲编辑
    scope: runtime
    license: official
    trigger:
      type: mode-only
      modes:
        - outline
---

## 大纲模式规则

- **大纲树** = 左侧「世界观」Tab 中的「大纲」子页，结构化节点（卷大纲 / 章节大纲 / 场景大纲）
- 工作流：list_outlines（可按 volumeId、parentId 过滤）→ create_outline / update_outline
- 删除前必须先 list_outlines 确认，再用 delete_outline
- 本模式**禁止**写入 Plan 文件或世界观条目；若用户要那些，提示切换到对应模式
- 不要输出大段正文续写
- 完成后告知已创建/更新的大纲节点标题与层级
',
    '1.0.0',
    true
  ),
(
    'polish-translate',
    '润色与翻译',
    '润色与翻译：保留原文信息，优化表达。用户粘贴片段要求润色、翻译、改写，或处于 Polish 模式时使用。',
    'editing',
    'official',
    '---
name: polish-translate
description: 润色与翻译：保留原文信息，优化表达。用户粘贴片段要求润色、翻译、改写，或处于 Polish 模式时使用。
metadata:
  author: narraverse
  version: "1.0.0"
  narraverse:
    displayName: 润色与翻译
    scope: runtime
    license: official
    trigger:
      type: mode-or-text
      modes:
        - polish
      textPattern: 润色|翻译|改写|优化文案|重写这句|polish|rewrite|translate
      textFlags: i
---

## 润色/翻译/改写规则

- **保留**原文核心信息、人物名、地名、专有名词一致性
- **保留**原文语气（幽默/严肃/抒情等），只在表达层面优化
- 改写时先确认目标风格（更简洁 / 更文学 / 更口语 / 更古风）
- 翻译时保留专业术语原文 + 首次出现加注
- 输出用 ```markdown 代码块包裹，标注「改写 / 翻译 / 润色」
- 不要复述或点评原文，直接给结果
',
    '1.0.0',
    true
  ),
(
    'story-planning',
    '故事规划',
    '故事规划：写入 Plan 规划文件，梳理故事结构与章节节拍。用户处于 Plan 规划模式时使用。',
    'planning',
    'official',
    '---
name: story-planning
description: 故事规划：写入 Plan 规划文件，梳理故事结构与章节节拍。用户处于 Plan 规划模式时使用。
metadata:
  author: narraverse
  version: "1.0.0"
  narraverse:
    displayName: 故事规划
    scope: runtime
    license: official
    trigger:
      type: mode-only
      modes:
        - plan
---

## 规划模式规则（Plan 文件优先）

- **Plan 文件** = 左侧「规划」区域的 Markdown 文档，是本模式的默认且首选产出
- 典型 path：plan/story-arc、plan/vol1-beats、plan/foreshadowing、plan/character-arcs
- 工作流：list_plan_files → read_plan_file（若存在）→ create_plan_file 或 update_plan_file
- 内容侧重：故事弧线、章节节拍、伏笔布局、角色动机、与已有正文的衔接
- create_outline / create_worldbook_entry **不能**在本模式使用；用户需要时提示切换「大纲 Outline」或「世界观 Worldbook」模式
- 不要输出大段正文续写；如需示例，控制在 2-3 句
- 完成后告知用户已写入的 plan path 与文件名，便于在左侧打开
',
    '1.0.0',
    true
  ),
(
    'worldbook-editing',
    '世界观编辑',
    '世界观编辑：读写世界观设定条目。用户处于 Worldbook 世界观模式时使用。',
    'worldbuilding',
    'official',
    '---
name: worldbook-editing
description: 世界观编辑：读写世界观设定条目。用户处于 Worldbook 世界观模式时使用。
metadata:
  author: narraverse
  version: "1.0.0"
  narraverse:
    displayName: 世界观编辑
    scope: runtime
    license: official
    trigger:
      type: mode-only
      modes:
        - worldbook
---

## 世界观模式规则

- **世界观库** = 左侧「世界观」Tab 中的「世界观」子页，按 category 分类的设定条目
- category：setting / location / item / faction / event / rule / character_lore / other
- 工作流：list_worldbook_entries（可按 category 过滤）→ read_worldbook_entry → create_worldbook_entry / update_worldbook_entry
- 删除前必须先 list 确认，再用 delete_worldbook_entry
- 本模式**禁止**写入 Plan 文件或大纲节点；若用户要那些，提示切换到对应模式
- 不要输出大段正文续写
- 完成后告知已创建/更新的设定条目标题与 category
',
    '1.0.0',
    true
  );
END;
$$;

REVOKE ALL ON FUNCTION public.seed_builtin_skill_catalog() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.seed_builtin_skill_catalog() TO authenticated;
GRANT EXECUTE ON FUNCTION public.seed_builtin_skill_catalog() TO service_role;

SELECT public.seed_builtin_skill_catalog();
